name: flutter_linter
description: linter for projects
version: 0.3.2
homepage: https://github.com/cenumi/flutter_linter.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/lint
  lint: ^2.1.2

  # https://pub.dev/packages/custom_lint
  custom_lint: ^0.5.1

  # https://pub.dev/packages/dart_code_metrics
#  dart_code_metrics: ^4.18.0

#dev_dependencies:
#  flutter_test:
#    sdk: flutter
