name: flutter_linter
description: linter for projects
version: 0.2.0
homepage: https://github.com/cenumi/flutter_linter.git

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/lint
  lint: ^2.0.1

  # https://pub.dev/packages/dart_code_metrics
#  dart_code_metrics: ^4.18.0

#dev_dependencies:
#  flutter_test:
#    sdk: flutter
