name: flutter_linter
description: linter for projects
version: 0.0.10
homepage: https://github.com/cenumi/flutter_linter.git

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/lint
  lint: ^1.10.0

  # https://pub.dev/packages/dart_code_metrics
  dart_code_metrics: ^4.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
